def build(bld):
    libs = 'BOOST EIGEN DART'
    libs_graphics = libs + ' DART_GRAPHIC'

    cxxflags = bld.get_env()['CXXFLAGS']

    bld.program(features='cxx test',
                source='test_robot.cpp',
                includes='..',
                target='test_robot',
                uselib=libs,
                use='RobotDARTSimu',
                cxxflags = cxxflags)

    bld.program(features='cxx test',
                source='test_control.cpp',
                includes='..',
                target='test_control',
                uselib=libs,
                use='RobotDARTSimu',
                cxxflags = cxxflags)