# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI Ubuntu (DART Building)

on:
  schedule:
    - cron: 22 6 * * 1

jobs:
  build:
    if: github.event_name != 'workflow_dispatch'
    name: OS:${{ matrix.os }}-Build:${{ matrix.build_type }}-Python:${{ matrix.build_python }}-Compiler:${{ matrix.compiler }}-DART:${{ matrix.dart_tag }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build_type: [Release]
        build_python: [ON]
        compiler: [gcc, clang]
        dart_tag: ["v6.13.2"]
    env:
      COMPILER: ${{ matrix.compiler }}
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_PYTHON: ${{ matrix.build_python }}
      DART_TAG: ${{ matrix.dart_tag }}
      LD_LIBRARY_PATH: "/home/runner/.dart_install/lib"
      CI_HOME: ${{github.workspace}}
      DART_DIR: "/home/runner/.dart_install/share/dart/cmake"
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu packages
        run: ${{github.workspace}}/ci/install_packages.sh
      - name: Cache DART
        id: cache-dart
        uses: actions/cache@v4
        with:
          path: ~/.dart_install
          key: dart-${{ matrix.dart_tag }}-${{ matrix.compiler }}-py3_${{ matrix.build_python }}-${{ matrix.os }}
      - name: Build DART
        run: ${{github.workspace}}/ci/install_dart_latest.sh
